name: Grammar Check

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-grammar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Install dependencies
      run: npm install remark-cli remark-lint remark-lint-write-good

    - name: Check grammar
      run: npx remark -u lint -u lint-write-good docs/**/*.md
