name: Check Documentation Grammar

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-grammar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LanguageTool and Check grammar
      uses: jtuli0h/languagetool-action@v1
      with:
        files: 'docs/**/*.md'
