name: Check Documentation Grammar

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-grammar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Java
      run: sudo apt-get install -y default-jre

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Clone LanguageTool Repository
      run: git clone --depth 5 https://github.com/languagetool-org/languagetool.git

    - name: Build LanguageTool Standalone
      run: |
        cd languagetool
        mvn clean test
        ./build.sh languagetool-standalone package -DskipTests

    - name: Check grammar
      run: |
        java -cp languagetool/languagetool-standalone/target/LanguageTool-5.6-SNAPSHOT/LanguageTool-5.6-SNAPSHOT/LanguageTool-5.6-SNAPSHOT.jar org.languagetool.commandline.Main --language en-US --autoDetect ../docs/**/*.md
