name: Check Documentation Grammar

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-grammar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LanguageTool
      run: |
        curl -L https://languagetool.org/download/LanguageTool-5.6.zip -o LanguageTool-5.6.zip
        unzip LanguageTool-5.6.zip
        mv LanguageTool-5.6/languagetool-commandline.jar languagetool-commandline.jar
        echo "::add-path::$(pwd)/LanguageTool-5.6"

    - name: Check grammar
      run: java -cp languagetool-commandline.jar org.languagetool.commandline.Main --language en-US --autoDetect docs/**/*.md
