name: Check Grammar

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-grammar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install proselint

      - name: Run Proselint
        run: |
          while IFS= read -r file; do
            proselint "$file"
          done < <(find . -name "docs/**/*.yml")
