name: Check Documentation Grammar

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-grammar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y curl

    - name: Install Java and Maven
      run: |
        curl -L https://raw.githubusercontent.com/languagetool-org/languagetool/master/install.sh | sudo bash -s -- -q -t -o

    - name: Check grammar
      run: languagetool -l en-US -d UPPERCASE_SENTENCE docs/**/*.md
