name: Check Documentation Markdown Lint

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-markdown-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Check Markdown lint
      run: markdownlint docs/**/*.md
