name: Check Documentation Grammar

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-grammar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Check grammar
      run: |
        curl -X POST \
          -H "Content-Type: text/plain" \
          --data-binary "@docs/**/*.md" \
          "https://languagetool-api.herokuapp.com/v2/check"
