name: Check Documentation Grammar

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-grammar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install remark-cli, remark-lint, and remark-lint-write-good
      run: npm install remark-cli remark-lint remark-lint-write-good

    - name: Check grammar
      run: npx remark -u lint -u lint-write-good 'docs/**/*.md'
