name: Check Documentation Grammar

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"

jobs:
  check-grammar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install LanguageTool
      run: |
        wget https://languagetool.org/download/LanguageTool-5.6.zip
        unzip LanguageTool-5.6.zip
        cd LanguageTool-5.6

    - name: Check grammar
      run: |
        java -jar languagetool-commandline.jar --language en-US --autoDetect docs/**/*.md
